GET http://localhost:8080/users

###
GET http://localhost:8080/users/12321

###
POST http://localhost:8080/users
Content-Type: application/json

{
    "first_name":"bob",
    "last_name":"last naem",
    "age":1123971
}

